#!/bin/bash
# [Gedit Tool]
# Applicability=all
# Input=nothing
# Name=Catkin Build
# Save-files=document
# Shortcut=F5
# Output=output-panel
# Languages=cpp

for package_name in `rospack list-names`
do
   if [[ `pwd` = */"$package_name"* ]]; then
     catkin build $package_name
     break
   fi
done
